### ISSUE TITLE
Legend element not styled in role="group"

### ISSUE THREAD

**Issue by ElDani82** [Yohn/PicoCSS#23]
## Describe the issue
I'm using `role="group"` to create a group of input elements akin to a radio group, but with buttons - mostly because both the HTML code (no separate labels necessary) and the styling are easier for what I need.

HTML has an appropriate element for that, `legend` is supposed to be used when describing not an individual element like a `label` would, but instead all elements of the parent `fieldset`.

This doesn't work with PicoCSS, because the legend element in such a scenario is entirely unstyled.

### Current Behavior
When used with a `label` element the code styles just fine, but the `legend` element is entirely unstyled.

### Expected Behavior
`legend` elements should behave the same as `label` elements.

### Reproduction URL
Example code on [CodePen](https://codepen.io/ElDani82/pen/yyBoabj).

### Environment
Windows 10, both current Chrome and Firefox

---

On a final note, I'm not sure if I should open a separate issue for this since it's related, but in the process of testing I found other styling issues too, with and without the use of a `label` element in a group. Some borders are either not shown (correctly) or are off by a pixel or two.

First, you'd logically expect a `primary` styled button to have preference over a `secondary` styled one. However, when two differently styled buttons are used in a group role, the one placed on the left will always be missing its right border, unless the element is in focus.

Second, when using a `label` in the `fieldset`, the adjoining button borders don't display correctly. Both left and right borders are inside the neighboring button by a pixel or two. This appears to only happen to buttons and not the label.

An example of that is in the CodePen link too, but if you can't reproduce, here's a screenshot to illustrate (open directly to avoid resizing in GitHub):

![image](https://github.com/user-attachments/assets/a27e1732-4048-4379-a32a-5c2636c03eeb)

**Comment by Yohn** [comment]
Hello, thanks for pointing this out!

For the border styling, I look a look at how bootstrap does the border style for the input groups, and outlined buttons, and saw that the right button border-left is shown as on top and not the primary or other color buttons - [Codepen.io](https://codepen.io/Yohn/pen/jENGmpd). I can see the need to try to change the borders when working with outlined elements but we can create another issue or discussion for that.

I just pushed an update to fix the rendering of the `legend` element within a `fieldset` element, or any element really, to match the labels, and to put the border back on labels within the group role. I also added the `.dropdown` component to be able to work within the group role since thats something I wanted to do with the groups.

I also noticed I had to put a `float:left` on legend when it was within a `fieldset[role=group]` but did not find why I had to do that. If anyone has any insight on why  thats the case, it would be great!

**Comment by Yohn** [comment]
@ElDani82 have you found anywhere online where a `fieldset` was used for a group / inline flex with a `legend` being inline with that group? I've been playing with this for a couple hours, and asking GitHub copilot, ChatGPT and Claude.ai for a solution, but I cannot get the legend to be inline on iOS #24
It is working for windows browsers but Apple just will not put that legend in the front.

[Here's a codepen](https://codepen.io/Yohn/pen/NPKwOVB) if anyone would like to give it a shot!

**Comment by ElDani82** [comment]
> have you found anywhere online where a `fieldset` was used for a group / inline flex with a `legend` being inline with that group?

Not that I can recall and in hindsight - after a bit of research myself - there's probably a good reason why this isn't done either.

What I did find were a couple of bug reports on the [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=653870) and [Chromium](https://issues.chromium.org/issues/41170870) bug-trackers that dealt with implementing an inline display for `legend` elements.

Or the lack of implementation in the case of Chromium, because they referenced the HTML specification and how this would go against them. I'm a CSS amateur at best, but the way I read the [HTML specification](https://html.spec.whatwg.org/multipage/rendering.html#rendered-legend) on the topic, it seems to say that `legend` elements would be displayed as a block inside a `fieldset` and browsers are even supposed to ignore display overrides such as inline:

> A [fieldset](https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element) element's [rendered legend](https://html.spec.whatwg.org/multipage/rendering.html#rendered-legend), if any, is expected to act as follows:
> - The element is expected to establish a new [formatting context](https://drafts.csswg.org/css-display/#formatting-context) for its contents. The type of this [formatting context](https://drafts.csswg.org/css-display/#formatting-context) is determined by its ['display'](https://drafts.csswg.org/css2/#display-prop) value, as usual.
> - The ['display'](https://drafts.csswg.org/css2/#display-prop) property **_is expected to behave as if its computed value was blockified_**.

With that out of the way, it's probably best to use a simple `div` or something else freely styleable in place of legend, but the trade-off is a loss of semantics and possibly accessibility. I'm thinking of doing something like this to deal with the latter:

```html
<div role="group">
    <div id="btn_legend">Sort By</div>
    <button aria-labelledby="btn_legend">Availability</button>
    <button aria-labelledby="btn_legend">Relative Profit</button>
    <button aria-labelledby="btn_legend">Absolute Profit</button>
</div>
```
